/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JSlider;
import javax.swing.JTextField;

/**
 *
 * @author xialas
 */
public class CadastroView extends javax.swing.JFrame {

    /**
     * Creates new form CadastroView
     */
    public CadastroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNameEstufa = new javax.swing.JLabel();
        lblNamePlanta = new javax.swing.JLabel();
        lblTempMax = new javax.swing.JLabel();
        lblTempMin = new javax.swing.JLabel();
        lblUmiMax = new javax.swing.JLabel();
        lblUmiMin = new javax.swing.JLabel();
        lblQtdLumens = new javax.swing.JLabel();
        nomeEstufaField = new javax.swing.JTextField();
        nomePlantaField = new javax.swing.JTextField();
        lumensField = new javax.swing.JTextField();
        temperaturaMaxField = new javax.swing.JTextField();
        temperaturaMinField = new javax.swing.JTextField();
        umidadeMaxField = new javax.swing.JTextField();
        umidadeMinField = new javax.swing.JTextField();
        salvarButton = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        sliderTempMaxima = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();
        jSlider4 = new javax.swing.JSlider();
        jSlider5 = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Estufas");
        setMinimumSize(new java.awt.Dimension(900, 500));
        setSize(new java.awt.Dimension(900, 500));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Estufa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 11))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(876, 453));
        jPanel1.setMinimumSize(new java.awt.Dimension(876, 453));
        jPanel1.setLayout(null);

        lblNameEstufa.setText("Nome da Estufa:");
        jPanel1.add(lblNameEstufa);
        lblNameEstufa.setBounds(17, 48, 87, 16);

        lblNamePlanta.setText("Nome da Planta:");
        jPanel1.add(lblNamePlanta);
        lblNamePlanta.setBounds(340, 50, 88, 16);

        lblTempMax.setText("Temperatura Máxima:");
        jPanel1.add(lblTempMax);
        lblTempMax.setBounds(17, 150, 116, 16);

        lblTempMin.setText("Temperatura Mínima:");
        jPanel1.add(lblTempMin);
        lblTempMin.setBounds(450, 150, 114, 16);

        lblUmiMax.setText("Umidade Máxima:");
        jPanel1.add(lblUmiMax);
        lblUmiMax.setBounds(17, 250, 97, 16);

        lblUmiMin.setText("Umidade Mínima:");
        jPanel1.add(lblUmiMin);
        lblUmiMin.setBounds(440, 260, 95, 16);

        lblQtdLumens.setText("Quantidade de Lumens:");
        jPanel1.add(lblQtdLumens);
        lblQtdLumens.setBounds(17, 345, 126, 16);
        jPanel1.add(nomeEstufaField);
        nomeEstufaField.setBounds(120, 47, 140, 22);

        nomePlantaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomePlantaFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nomePlantaField);
        nomePlantaField.setBounds(440, 47, 140, 22);

        lumensField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lumensFieldActionPerformed(evt);
            }
        });
        jPanel1.add(lumensField);
        lumensField.setBounds(370, 340, 30, 22);
        jPanel1.add(temperaturaMaxField);
        temperaturaMaxField.setBounds(370, 150, 30, 22);
        jPanel1.add(temperaturaMinField);
        temperaturaMinField.setBounds(800, 150, 30, 22);
        jPanel1.add(umidadeMaxField);
        umidadeMaxField.setBounds(370, 250, 30, 22);
        jPanel1.add(umidadeMinField);
        umidadeMinField.setBounds(800, 260, 30, 22);

        salvarButton.setText("SALVAR");
        salvarButton.setMaximumSize(new java.awt.Dimension(900, 500));
        salvarButton.setMinimumSize(new java.awt.Dimension(900, 500));
        jPanel1.add(salvarButton);
        salvarButton.setBounds(100, 400, 72, 22);
        jPanel1.add(jSlider1);
        jSlider1.setBounds(150, 340, 200, 20);
        jPanel1.add(sliderTempMaxima);
        sliderTempMaxima.setBounds(150, 150, 200, 20);
        jPanel1.add(jSlider3);
        jSlider3.setBounds(580, 150, 200, 20);
        jPanel1.add(jSlider4);
        jSlider4.setBounds(150, 250, 200, 20);
        jPanel1.add(jSlider5);
        jSlider5.setBounds(580, 260, 200, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lumensFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lumensFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lumensFieldActionPerformed

    private void nomePlantaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePlantaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePlantaFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider5;
    private javax.swing.JLabel lblNameEstufa;
    private javax.swing.JLabel lblNamePlanta;
    private javax.swing.JLabel lblQtdLumens;
    private javax.swing.JLabel lblTempMax;
    private javax.swing.JLabel lblTempMin;
    private javax.swing.JLabel lblUmiMax;
    private javax.swing.JLabel lblUmiMin;
    private javax.swing.JTextField lumensField;
    private javax.swing.JTextField nomeEstufaField;
    private javax.swing.JTextField nomePlantaField;
    private javax.swing.JButton salvarButton;
    private javax.swing.JSlider sliderTempMaxima;
    private javax.swing.JTextField temperaturaMaxField;
    private javax.swing.JTextField temperaturaMinField;
    private javax.swing.JTextField umidadeMaxField;
    private javax.swing.JTextField umidadeMinField;
    // End of variables declaration//GEN-END:variables

    public JTextField getLumensField() {
        return lumensField;
    }

    public void setLumensField(JTextField lumensField) {
        this.lumensField = lumensField;
    }

    public JTextField getNomeEstufaField() {
        return nomeEstufaField;
    }

    public void setNomeEstufaField(JTextField nomeEstufaField) {
        this.nomeEstufaField = nomeEstufaField;
    }

    public JTextField getNomePlantaField() {
        return nomePlantaField;
    }

    public void setNomePlantaField(JTextField nomePlantaField) {
        this.nomePlantaField = nomePlantaField;
    }

    public JTextField getTemperaturaMaxField() {
        return temperaturaMaxField;
    }

    public void setTemperaturaMaxField(JTextField temperaturaMaxField) {
        this.temperaturaMaxField = temperaturaMaxField;
    }

    public JTextField getTemperaturaMinField() {
        return temperaturaMinField;
    }

    public void setTemperaturaMinField(JTextField temperaturaMinField) {
        this.temperaturaMinField = temperaturaMinField;
    }

    public JTextField getUmidadeMaxField() {
        return umidadeMaxField;
    }

    public void setUmidadeMaxField(JTextField umidadeMaxField) {
        this.umidadeMaxField = umidadeMaxField;
    }

    public JTextField getUmidadeMinField() {
        return umidadeMinField;
    }

    public void setUmidadeMinField(JTextField umidadeMinField) {
        this.umidadeMinField = umidadeMinField;
    }

    public JButton getSalvarButton() {
        return salvarButton;
    }

    public void setSalvarButton(JButton salvarButton) {
        this.salvarButton = salvarButton;
    }

    public JSlider getSliderTempMaxima() {
        return sliderTempMaxima;
    }

    public void setSliderTempMaxima(JSlider sliderTempMaxima) {
        this.sliderTempMaxima = sliderTempMaxima;
    }
    
}
